services:
  cosmoport1:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    environment:
      - ASP_INSTANCE_NAME=vozmite
    networks:
      - bit_net

  cosmoport2:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    environment:
      - ASP_INSTANCE_NAME=na
    networks:
      - bit_net

  cosmoport3:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    environment:
      - ASP_INSTANCE_NAME=practicu
    networks:
      - bit_net

  cosmoport4:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    environment:
      - ASP_INSTANCE_NAME=pj
    networks:
      - bit_net

  dispatcher:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cosmoport1
      - cosmoport2
      - cosmoport3
      - cosmoport4
    restart: always
    networks:
      - bit_net

networks:
  bit_net: